In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
# Convert categorical feature Gender into a nummercial feature
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [4]:
# Convert categorical feature Geography into a nummercial feature

one_hot_encoder_geography = OneHotEncoder()
geography = one_hot_encoder_geography.fit_transform(data['Geography'].values.reshape(-1,1)).toarray()
geography = pd.DataFrame(geography, columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))
data = pd.concat([data.reset_index(drop=True), geography], axis=1)

In [6]:
data.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,6,15574012,Chu,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,7,15592531,Bartlett,822,France,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,8,15656148,Obinna,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,9,15792365,He,501,France,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,10,15592389,H?,684,France,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

In [7]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname', 'Geography'], axis=1)

In [8]:
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

In [12]:
# Split the data into dependent and independent variables
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [13]:
# Split the data into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Scale the features

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
X_train.shape

(8000, 12)

In [17]:
X_test.shape

(2000, 12)

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
# Save the encoders and scaler for later use

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file) # Save the label encoder_gender

with open('one_hot_encoder_geography.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geography, file) # Save the one_hot_encoder_geography
    
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file) # Save the scaler

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
# Build the model

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression 
])

## compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

/opt/homebrew/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
# Model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from datetime import datetime

# Setup TensorBoard log
log_dir = 'regression_logs/fit/' + datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboar_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [25]:
# Set-up EarlyStopping callback
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [29]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback, early_stopping_callback])

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - loss: 101034.4453 - mae: 101034.4453 - val_loss: 98484.1953 - val_mae: 98484.1953
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 99326.3594 - mae: 99326.3594 - val_loss: 96740.0000 - val_mae: 96740.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - loss: 95997.7344 - mae: 95997.7344 - val_loss: 92347.8438 - val_mae: 92347.8438
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - loss: 93271.9141 - mae: 93271.9141 - val_loss: 85162.8750 - val_mae: 85162.8750
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - loss: 83882.2500 - mae: 83882.2500 - val_loss: 76109.7109 - val_mae: 76109.7109
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - loss: 74741.1250 - mae: 74741.1250 - val_loss: 67124.7969 - val_mae: 67124.7969
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - loss: 65375.9609 - mae: 65375.9609 - val_loss: 59702.2070 - val_mae: 59702.2070
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - loss: 58132.1953 - mae: 58132.1953 - val_loss: 54774.3555 - val_mae: 54774.3555
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - loss: 54403.1914 - mae: 54403.1914 - val_loss: 52251.8398 - val_mae: 52251.8398
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - loss: 51618.3281 - mae: 51618.3281 - val_loss: 51339.5000 - val_mae: 51339.5000
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - loss: 51069.8242 - mae: 51069.8242 - val_loss: 51083.1445 - val_mae: 51083.1445
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - loss: 50559.7578 - mae: 50559.7578 - val_loss: 50984.3281 - val_mae: 50984.3281
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - loss: 50383.8398 - mae: 50383.8398 - val_loss: 50917.1758 - val_mae: 50917.1758
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - loss: 51046.2227 - mae: 51046.2227 - val_loss: 50859.7773 - val_mae: 50859.7773
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - loss: 50615.2773 - mae: 50615.2773 - val_loss: 50810.6680 - val_mae: 50810.6680
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - loss: 50146.5547 - mae: 50146.5547 - val_loss: 50754.9219 - val_mae: 50754.9219
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - loss: 49904.1602 - mae: 49904.1602 - val_loss: 50703.5547 - val_mae: 50703.5547
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 50115.4570 - mae: 50115.4570 - val_loss: 50681.7266 - val_mae: 50681.7266
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - loss: 50019.8398 - mae: 50019.8398 - val_loss: 50637.8516 - val_mae: 50637.8516
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - loss: 50279.3789 - mae: 50279.3789 - val_loss: 50603.1953 - val_mae: 50603.1953
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - loss: 49804.7891 - mae: 49804.7891 - val_loss: 50566.1680 - val_mae: 50566.1680
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - loss: 50136.0195 - mae: 50136.0195 - val_loss: 50532.8320 - val_mae: 50532.8320
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - loss: 50229.1250 - mae: 50229.1250 - val_loss: 50511.4570 - val_mae: 50511.4570
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - loss: 49853.5273 - mae: 49853.5273 - val_loss: 50492.2812 - val_mae: 50492.2812
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - loss: 49907.0234 - mae: 49907.0234 - val_loss: 50472.9531 - val_mae: 50472.9531
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - loss: 49769.0117 - mae: 49769.0117 - val_loss: 50449.4023 - val_mae: 50449.4023
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 50308.2969 - mae: 50308.2969 - val_loss: 50446.5430 - val_mae: 50446.5430
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - loss: 49292.9102 - mae: 49292.9102 - val_loss: 50428.2148 - val_mae: 50428.2148
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - loss: 49632.9727 - mae: 49632.9727 - val_loss: 50411.8867 - val_mae: 50411.8867
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - loss: 49985.6406 - mae: 49985.6406 - val_loss: 50386.7227 - val_mae: 50386.7227
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - loss: 49306.5898 - mae: 49306.5898 - val_loss: 50376.0469 - val_mae: 50376.0469
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 49822.1055 - mae: 49822.1055 - val_loss: 50361.9453 - val_mae: 50361.9453
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - loss: 49889.5977 - mae: 49889.5977 - val_loss: 50354.7734 - val_mae: 50354.7734
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - loss: 49894.0898 - mae: 49894.0898 - val_loss: 50352.8750 - val_mae: 50352.8750
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 50253.6875 - mae: 50253.6875 - val_loss: 50325.9922 - val_mae: 50325.9922
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - loss: 49590.4844 - mae: 49590.4844 - val_loss: 50322.5547 - val_mae: 50322.5547
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - loss: 49887.2617 - mae: 49887.2617 - val_loss: 50313.6133 - val_mae: 50313.6133
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - loss: 49713.5000 - mae: 49713.5000 - val_loss: 50311.1094 - val_mae: 50311.1094
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - loss: 49383.1328 - mae: 49383.1328 - val_loss: 50300.6992 - val_mae: 50300.6992
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - loss: 50222.1094 - mae: 50222.1094 - val_loss: 50309.7812 - val_mae: 50309.7812
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - loss: 49547.6914 - mae: 49547.6914 - val_loss: 50284.6602 - val_mae: 50284.6602
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - loss: 49614.6328 - mae: 49614.6328 - val_loss: 50287.2148 - val_mae: 50287.2148
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - loss: 49241.4062 - mae: 49241.4062 - val_loss: 50288.8242 - val_mae: 50288.8242
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - loss: 49265.4453 - mae: 49265.4453 - val_loss: 50279.0195 - val_mae: 50279.0195
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - loss: 49644.8594 - mae: 49644.8594 - val_loss: 50273.1406 - val_mae: 50273.1406
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - loss: 49516.1016 - mae: 49516.1016 - val_loss: 50265.1875 - val_mae: 50265.1875
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - loss: 48925.8945 - mae: 48925.8945 - val_loss: 50271.9492 - val_mae: 50271.9492
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - loss: 49647.9766 - mae: 49647.9766 - val_loss: 50269.3984 - val_mae: 50269.3984
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 50163.7539 - mae: 50163.7539 - val_loss: 50268.3984 - val_mae: 50268.3984
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - loss: 49654.9883 - mae: 49654.9883 - val_loss: 50259.6445 - val_mae: 50259.6445
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - loss: 50280.8281 - mae: 50280.8281 - val_loss: 50254.8320 - val_mae: 50254.8320
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - loss: 49289.2773 - mae: 49289.2773 - val_loss: 50254.6445 - val_mae: 50254.6445
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - loss: 49398.2734 - mae: 49398.2734 - val_loss: 50255.6406 - val_mae: 50255.6406
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - loss: 49701.9688 - mae: 49701.9688 - val_loss: 50252.9609 - val_mae: 50252.9609
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - loss: 50365.7695 - mae: 50365.7695 - val_loss: 50246.1523 - val_mae: 50246.1523
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - loss: 49345.8672 - mae: 49345.8672 - val_loss: 50248.3047 - val_mae: 50248.3047
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - loss: 49162.9453 - mae: 49162.9453 - val_loss: 50243.5430 - val_mae: 50243.5430
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - loss: 49027.8398 - mae: 49027.8398 - val_loss: 50246.8125 - val_mae: 50246.8125
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - loss: 48955.3750 - mae: 48955.3750 - val_loss: 50245.8867 - val_mae: 50245.8867
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - loss: 49292.4258 - mae: 49292.4258 - val_loss: 50255.1758 - val_mae: 50255.1758
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - loss: 49671.9883 - mae: 49671.9883 - val_loss: 50238.2305 - val_mae: 50238.2305
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - loss: 49395.2617 - mae: 49395.2617 - val_loss: 50240.7305 - val_mae: 50240.7305
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - loss: 49311.9062 - mae: 49311.9062 - val_loss: 50242.3711 - val_mae: 50242.3711
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - loss: 49118.9062 - mae: 49118.9062 - val_loss: 50236.6172 - val_mae: 50236.6172
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - loss: 48803.1680 - mae: 48803.1680 - val_loss: 50233.7617 - val_mae: 50233.7617
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - loss: 49172.8516 - mae: 49172.8516 - val_loss: 50233.5312 - val_mae: 50233.5312
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 48960.6875 - mae: 48960.6875 - val_loss: 50237.9219 - val_mae: 50237.9219
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - loss: 49236.9180 - mae: 49236.9180 - val_loss: 50237.2344 - val_mae: 50237.2344
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - loss: 49578.1211 - mae: 49578.1211 - val_loss: 50244.8086 - val_mae: 50244.8086
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - loss: 49221.2266 - mae: 49221.2266 - val_loss: 50243.7773 - val_mae: 50243.7773
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - loss: 49437.3008 - mae: 49437.3008 - val_loss: 50241.1133 - val_mae: 50241.1133

In [30]:
## Evaluate the model

%load_ext tensorboard

In [32]:
#%tensorboard --regresssionlogs/fit
%tensorboard --logdir regression_logs/fit

In [33]:
## Evaluate the model on the test data

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Mae: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - loss: 51096.0039 - mae: 51096.0039
Test Mae: 50233.53125

In [34]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.